# autogenerated using SnoopCompile.jl

function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing

    @info "Forced precompilation running..."

    isdefined(ArgParse, Symbol("##parse_args#51")) && precompile(Tuple{getfield(ArgParse, Symbol("##parse_args#51")),Bool,typeof(ArgParse.parse_args),Array{T,1} where T,ArgParse.ArgParseSettings})
    precompile(Tuple{Core.kwftype(typeof(ArgParse.add_arg_field)),Any,typeof(ArgParse.add_arg_field),ArgParse.ArgParseSettings,Union{Array{T,1}, T} where T<:AbstractString})

    precompile(Tuple{typeof(Instractor.main),Array{String,1}})
end